### PR TITLE
Add database param for rows queries if exists

### LINKED ISSUE #478: Rows queries not supporting database defined in client connection
The /v1/rows REST endpoint supports a database parameter for specifying an alternative db, but the Node.js Client API currently does not pass along the db from the DatabaseClient connection configuration. It should.

To reproduce, just make an Optic query using a db client whose connection config specifies an alternative db. For example, set up the SQLdata db and content from the SQL quick start (http://docs.marklogic.com/guide/sql/setup) and then try to query it via port 8000 using Node.js. 

I used that setup and this query:
```
const marklogic = require('marklogic');
const my = require('./my-connection.js');

const db = marklogic.createDatabaseClient(my.connInfo);
const pb = marklogic.planBuilder;

db.rows.query(
  pb.fromView('main', 'employees')
    .select(['EmployeeID', 'FirstName', 'LastName'])
    .orderBy('EmployeeID')
    .limit(3)
).then( function(rows) {
    console.log(JSON.stringify(rows, null, 2));
}).catch(
  function(error) {
    console.log('ERROR:');
    console.log(JSON.stringify(error, null, 2));
});
```

Originally, my db config looked like this:
```
module.exports = {
  connInfo: {
    host: 'myhost',
    port: 8000,
    user: 'myuser',
    password: 'mypassword',
    database: 'SQLdata'
  }
};
```
If you try that, the server squawks that there is no suitable view because it is trying to use Documents. It only started working when I created a REST instance with the following config and changed my connection info to match in Node.js.
```
{"rest-api": {
  "name": "optic-test",
  "database": "SQLdata",
  "port": "8005"
}}
```
I had also confirmed that a raw rest call that included the equivalent plan and `database=SQLdata` worked fine.

(Sorry, @wooldridge , I had to tag this as 2.1.1 because there's not 2.1.2 milestone defined yet.)

### PR DESCRIPTION
**Pull request by wooldridge**
Also add test for this. Fixes #478.

### CODE REVIEW

**Comment by wooldridge** [comment]
@ehennum, the update to have the client db tests use the 'rest-evaluator' user passes those tests.

**Comment by ehennum** [comment]
Thanks for fixing up the unit test.

**Comment by ayuwono** [comment]
Ok, looks good

**Comment by wooldridge** [comment]
Approved by mrtriage.

**Pull request merged**
