### PR TITLE
NODE-88 : Update copyright year in the files.

### PR DESCRIPTION
**Pull request by anu3990**
https://project.marklogic.com/jira/browse/NODE-88

### CODE REVIEW

**Review by georgeajit — COMMENTED** [review]
Make sure to pull in changes for security vulnerabilities release into develop branch

**Comment by anu3990** [comment]
Hi @georgeajit , the changes were added to the "develop" branch. I also added an "npm audit" in the jenkins that generates this report on every run - https://jenkins.marklogic.com/view/Node%20API/job/MLServer_11/job/NodeAPIUnitTests_develop_xdmp_develop/ws/npm-audit-report.json

**Review by rjrudin — COMMENTED** [review]
What's the reason for not doing 2022 for every file?

**Comment by anu3990** [comment]
Hi @rjrudin , based on the list sent by Anadi , not all the files were modified in 2022. We are changing the copyright to the year they were last modified. @anadisharmaa please correct me if i am wrong.
Thanks.!

**Comment by anadisharmaa** [comment]
Looks good to me!

**Comment by anadisharmaa** [comment]
> Hi @rjrudin , based on the list sent by Anadi , not all the files were modified in 2022. We are changing the copyright to the year they were last modified. @anadisharmaa please correct me if i am wrong. Thanks.!

That's right. Changes look good to me!

**Review by anadisharmaa — APPROVED** [review]

**Review by rjrudin — APPROVED** [review]

**Pull request merged**
