### PR TITLE
fix(#303): Update README with compatibility info

### LINKED ISSUE #303: Earlier versions of Client API should work with later versions of MarkLogic
Version 1.x of the Node.js Client API (compatible with ML8) should also work with ML9, but not support new features available in ML9. (If developers need to use new ML9 features, they will be required to upgrade to 2.x.)

This task is to check 1.x compatibility with ML9 upon the release of ML9 to make sure this is the case. Per discussion with @jmakeig.

### PR DESCRIPTION
**Pull request by wooldridge**
Fixes #303

### CODE REVIEW

**Comment by wooldridge** [comment]
@ayuwono, what's the easiest way to run Node.js Client API tests on the earliest and latest versions of ML8? I would like to substantiate that the upcoming release works on all versions of 8, and proving that it works on the earliest and latest would be strong proof of this. I've actually already run the tests on 8.0-6.3, so what I'm really looking for is the first version of ML8.

**Comment by wooldridge** [comment]
@jmakeig, here's what we get in the current docs generation when we use  [@since](http://usejsdoc.org/tags-since.html)):

20170315_since_jsdoc

It would be great to add that info across the API docs. It would take some sleuthing to determine each method came into being.

**Comment by kcoleman-marklogic** [comment]
At this stage, you can probably get away with tagging everything with 1.0, except what's new in 2.0-1. The whole API was new for 8.0-1, and while there were a few functional changes (like being able to pass multiple URIs to Documents.remove), I don't think any new functions or interfaces were added in 8.0-x.

The thing I always wonder about with a feature like this (we get requests for the XQuery docs, too) is what is the contract, really? Like in the example I gave above, Documents.remove was there from the beginning, but had its functionality extended. Does that get a version bump or not? Just one of those "inquiring minds want to know" things. :)

**Comment by ayuwono** [comment]
@wooldridge, are you looking for the earliest version of ML8 (like 8.0-6.1)? You can find it at /project/engineering/builds/

**Comment by wooldridge** [comment]
I've updated the JSDoc information with  [@since](http://usejsdoc.org/tags-since.html) tags. All methods and namespaces are marked version 1.0 except for the following:
```
documents.protect()
documents.wipe()
documents.protectResult()
documents.wipeResult()
patchBuilder.patchBuilderMetadataValues
patchBuilderMetadataValues.add()
patchBuilderMetadataValues.remove()
patchBuilderMetadataValues.replace()
queryBuilder.falseQuery()
queryBuilder.geospatialRegion()
queryBuilder.minDistance()
queryBuilder.trueQuery()
queryBuilder.MinDistanceParam
```

**Comment by wooldridge** [comment]
I also updated the README to specify that 2.0.1 has been tested successfully with 8.0-6.3 and 9.0-1, which is true.  I discussed this with @ehennum, and he said this aligns with the rolling upgrade requirements for the client APIs: MarkLogic must offer clients that work with the latest release of the current version (e.g. 9.0-1) and the latest release of the previous version (e.g. 8.0-6.3). 

Erik and I also discussed the need for specifying version compatibility with each our tests for more efficient testing of API compatibility with MarkLogic versions. I could then run 2.0.1 on ML 8.0-6.3 and have it skip the tests for new features in 9.0-1.

**Comment by wooldridge** [comment]
I'm going to merge this and close the associated issue (#303). We can fine tune the README as @jmakeig prepares release notes (https://github.com/marklogic/node-client-api/issues/327).

**Pull request merged**
